### ISSUE TITLE
StripeElement Not Defined

### ISSUE THREAD

**Issue by devsamuelv** [niteshpurohit/ngx-stripe#6]
In the documentation the element: StripeElement, is that a type I have create or is it included in the package

error message `Cannot find name 'StripeElement' ts(2304)`

**Comment by niteshpurohit** [comment]
I don't know the full context what you are trying to do. But, From the error message i can suggest below.
```
import { Element as StripeElement } from '@niteshp/ngx-stripe';
```

I will update readme file with this correction. 
Thanks for posting issue.

**Comment by devsamuelv** [comment]
ok thanks it fixed my problem
